version: "3.8"

services:
  frontend:
    container_name: example_frontend
    build: ./example-frontend
    environment:
      REACT_APP_BACKEND_URL: http://localhost:80
  backend:
    container_name: example_backend
    build: ./example-backend
    environment:
      REDIS_HOST: redis
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
      REQUEST_ORIGIN: http://localhost:80
    depends_on:
      - redis
      - postgres
    ports:
      - 8080:8080
  redis:
    container_name: redis_host
    image: redis
    restart: unless-stopped
  postgres:
    container_name: postgres_db
    image: postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: testdb
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf