version: "3.8"

services:
  frontend:
    container_name: example_frontend
    build: ./example-frontend
    depends_on:
    - backend
    ports:
      - 5000:5000
  backend:
    container_name: example_backend
    build: ./example-backend
    environment:
      REDIS_HOST: redis
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
    depends_on:
      - redis
      - postgres
    ports:
      - 8080:8080
  redis:
    container_name: redis_host
    image: redis
    restart: unless-stopped
  postgres:
    container_name: postgres_db
    image: postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: testdb