version: "3.8"

services:
  frontend:
    container_name: example_frontend
    build: ./example-frontend
    ports:
      - 5000:5000
  backend:
    container_name: example_backend
    build: ./example-backend
    ports:
      - 8080:8080
